### ISSUE TITLE
Roadmap ?

### ISSUE THREAD

**Issue by AmauryVanEspen** [yarielg/quest-asap#1]
Hello
what is your roadmap for the plugin and integration ?
Thank you
Amaury

**Comment by yarielg** [comment]
Hello Amaury

 This project starts because a  client asked me for an integration with his Ecommerce website and his SAP b1 database. I started it with a big expectation, I wanted to create this plugin but te client just wanted show some basic functionalities, so this plugin just makes some basic requirement. I would like to take this most serious because this project could have a big impact, as you should know SAP B1 is very used and the same with woocommerce so this integration would be amazing, I'm working in other projects, so I've had not time to continue and less to create a Roadmap or any artefact.

![quest-asap](https://user-images.githubusercontent.com/42778527/60400843-c1ec8f80-9b47-11e9-953a-10a1f12c14cb.png)

![price-list-sapb1](https://user-images.githubusercontent.com/42778527/60400915-6a025880-9b48-11e9-9a1d-3587bf51ca5e.png)

Regards

**Comment by AmauryVanEspen** [comment]
Hello,

there is already some interesting integration
loading orders for example and managing stock availability
let me know if you wish to work on it
Best

Amaury

**Comment by yarielg** [comment]
Yes, of course, why not, I would like to work on it

**Comment by AmauryVanEspen** [comment]
Hello @yarielg 
still interested in working on the subject ?
Regards
Amaury
